# Generated by Django 5.2.5 on 2025-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0002_subtask_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
