# Generated by Django 5.2.5 on 2025-10-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0003_alter_subtask_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='slug',
        ),
    ]
