# Generated by Django 5.2.5 on 2025-09-25 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number please.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Latin letters, digits and -/_ only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+\\Z', 'Enter a valid username. This value may contain only latin letters, numbers, and -/_ characters.')]),
        ),
    ]
