# Generated by Django 5.2.5 on 2025-11-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('tags', '0001_initial'),
        ('tags', '0002_alter_tag_tasks'),
        ('tags', '0003_alter_tag_tasks'),
        ('tags', '0004_alter_tag_name'),
        ('tags', '0005_tag_slug'),
        ('tags', '0006_alter_tag_slug')
    ]

    dependencies = [
        ('tasks', '0006_category_user'),
        ('tasks', '0007_remove_task_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tasks', models.ManyToManyField(
                    blank=True,
                    related_name='tags',
                    to='tasks.task'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
