# Generated by Django 5.2.5 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_tasks'),
        ('tasks', '0007_remove_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tasks.task'),
        ),
    ]
