# Generated by Django 5.2.5 on 2025-10-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
    ]
