# Generated by Django 5.2.5 on 2025-10-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_remove_tag_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
