# Generated by Django 5.2.5 on 2025-08-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_description_alter_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comment',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
