# Generated by Django 5.2.5 on 2025-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_remove_tag_tasks'),
        ('tasks', '0007_remove_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tags.tag'),
        ),
    ]
